// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// SECURITY FIX: Use environment variables instead of hardcoded keys
const SUPABASE_URL = "https://yhthxtppnnumtbfucbpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlodGh4dHBwbm51bXRiZnVjYnBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxODc3NDIsImV4cCI6MjA3MTc2Mzc0Mn0.QF7rYW1Uemym6WOW-EMid-rHjO23iRy53lORYSPyFX4";

// Validate required environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing required Supabase configuration. Please check your project setup.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// SECURITY FIX: Use secure storage instead of localStorage
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'trading-app-auth',
    flowType: 'pkce'
  },
  global: {
    headers: {
      'x-application-name': 'trading-analytics-platform'
    }
  }
});